variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: python:latest


before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_SSH_PRIV_KEY")

deploy-to-stage:
  stage: deploy
  script:
  - pip install lektor
  - lektor build -f jsminify -f scss --output-path staging-webseite
  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp staging-webseite "$USERNAME@$DOMAIN:$DOMAIN/staging-$CI_COMMIT_REF_NAME"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://release.maxbachmann.de/staging-$CI_COMMIT_REF_NAME
  except:
  - master


deploy-to-prod:
  stage: deploy
  script:
  - pip install lektor
  - lektor build -f jsminify -f scss --output-path staging-webseite
  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp staging-webseite "$USERNAME@$DOMAIN:$DOMAIN"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://release.maxbachmann.de/staging-$CI_COMMIT_REF_NAME
  only:
  - master


