lektor:build:
  stage: build
  image: python:latest
  script:
  - pip install lektor
  - lektor build -f jsminify -f scsscompile --output-path build
  - cd build
  - tar -cJvf build.tar.gz ./*
  - mv build.tar.gz ../build.tar.gz
  artifacts:
    paths:
      - build.tar.gz


deploy-to-stage:
  stage: deploy
  image: debian:stable
  variables:
    GIT_STRATEGY: none
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_SSH_PRIV_KEY")
  script:
  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p build.tar.gz "$USERNAME@$DOMAIN:tmp"
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USERNAME@$DOMAIN "mkdir -p webseite/staging-$CI_COMMIT_REF_NAME && tar -xJvf /tmp/build.tar.gz -C webseite/staging-$CI_COMMIT_REF_NAME"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://toolbox-bodensee.de/staging-$CI_COMMIT_REF_NAME
  dependencies:
  - lektor:build
  except:
  - master


deploy-to-prod:
  stage: deploy
  image: debian:stable
  variables:
    GIT_STRATEGY: none
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_SSH_PRIV_KEY")
  script:
  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p build.tar.gz "$USERNAME@$DOMAIN:tmp"
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USERNAME@$DOMAIN "tar -xJvf /tmp/build.tar.gz -C webseite"
  dependencies:
  - lektor:build
  only:
  - master


