language: python
python: 3.6
git:
  lfs_skip_smudge: true
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - git lfs pull
install: 
  - "pip install Lektor"
  - git clone https://github.com/sass/sassc.git
  - . sassc/script/bootstrap
  - make -C sassc -j4
  - make sass
script: "lektor build"
before_deploy: "echo 'c3woc.de ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC5NslYj+wtriBuKIxJfDRm9E2hnlstWR8durQ6pKvVvP7wjcoXIyAxe41GvJ9SoEhSjF7oVlzlw+zAkzl5WOZ4=' > ~/.ssh/known_hosts"
deploy:
  provider: script
  script: "lektor deploy --key $LEKTOR_DEPLOY_KEY toolbox"
after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then deployment/deploy_pullrequest.sh; fi'
