language: python
python: 3.6
git:
  lfs_skip_smudge: true
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - git lfs pull
install: 
  - pip install lektor
  - if hash apt 2>/dev/null; then sudo apt update; sudo apt install imagemagick -y; elif hash pacman 2>/dev/null; then sudo pacman -Sy imagemagick --noconfirm; elif hash dnf 2>/dev/null; then sudo dnf install -y ImageMagick; else echo -e "Please install Imagemagick"; fi
  - git clone https://github.com/sass/sassc.git
  - . sassc/script/bootstrap
  - make -C sassc -j4
  - ./sassc/bin/sassc -t compressed ./assets/sass/main.scss ./assets/css/main.min.css
  - ./sassc/bin/sassc -t compressed ./assets/sass/ie9.scss ./assets/css/ie9.min.css
  - lektor clean --yes
  - lektor build
script: "lektor build"
before_deploy: "echo 'c3woc.de ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC5NslYj+wtriBuKIxJfDRm9E2hnlstWR8durQ6pKvVvP7wjcoXIyAxe41GvJ9SoEhSjF7oVlzlw+zAkzl5WOZ4=' > ~/.ssh/known_hosts"
deploy:
  provider: script
  script: "lektor deploy --key $LEKTOR_DEPLOY_KEY toolbox"
after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then deployment/deploy_pullrequest.sh; fi'
