language: python
python: 3.6
git:
  lfs_skip_smudge: true
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/yarn
    - $HOME/.cache/lektor/builds
    
services:
  - docker
  

before_install:
  - git lfs pull
  - ls -a
  - docker pull ubuntu
  - docker run -v /host/directory:/container/directory ubuntu /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"

script: "lektor build -f webpack"
